name: Build Workflows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine
    steps:
      - name: Run Build
        run: echo "build"
